# Jekyll 配置文件

# 网站基本信息
title: "MaxizYB's Blog"
description: "A personal blog powered by Jekyll."
quote: "Coding is tiring, you need relaxing."  # 添加网站引言
author: "MaxizYB"
email: "your-email@example.com"
url: "https://maxizyb.github.io"
baseurl: "" # 如果托管在子目录中，设置子目录路径，例如 "/blog"

# 构建设置
theme: minima
markdown: kramdown
paginate: 5 # 每页显示的文章数量
paginate_path: "/page:num/" # 分页路径

# 插件
plugins:
  - jekyll-feed # RSS 订阅
  - jekyll-sitemap # 站点地图
  - jekyll-seo-tag # SEO 优化
  - jekyll-paginate # 分页功能

# 排除文件/文件夹
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md

# 默认值
defaults:
  - scope:
      path: "" # 适用于所有文件
      type: "posts"
    values:
      layout: "post"
      author: "MaxizYB"

# Markdown 设置
kramdown:
  input: GFM # 支持 GitHub 风格的 Markdown
  auto_ids: true
  syntax_highlighter: rouge # 代码高亮